### ISSUE TITLE
How to get the processed_trans.npy file

### ISSUE THREAD

**Issue by UttaranB127** [david-yoon/multimodal-speech-emotion#10]
`IEMOCAP_02_to_four_category.ipynb` looks for a file called `procesed_trans.npy` in part 07-A, cell 42:

```
data = np.load('../data/processed/IEMOCAP/processed_trans.npy')
```

Apparently, it contains 128-dimensional features for every data point. But I could not find any part of the code that generates this .npy file. The closest I found was generating a `precessed_tran.csv` file in `IEMOCAP_00_extract_label_transcription.ipynb`. This file generates the session ids and the raw text transcriptions as strings. How can I convert these raw values to the 128-dimensional features in the .npy file?

**Comment by david-yoon** [comment]
Please refer to the following notebook that contains the process to generate "processed_trans.npy."

https://github.com/david-yoon/multimodal-speech-emotion/blob/master/preprocessing/IEMOCAP_NLP_01_Transcription_to_Index.ipynb

**Comment by UttaranB127** [comment]
Thanks
