### ISSUE TITLE
Can you provide WAP code?Thanks!

### ISSUE THREAD

**Issue by OnlyAoiKunie** [david-yoon/multimodal-speech-emotion#13]
Hello, David.
I saw your paper and ran the code.
I get a confusion matrix after running the analysis/Confusion_Matrix.ipynb.
But I can't get WAP to evaluate my result.
Can you provide WAP code?
Or can I just compute WAP from confusion matrix?
Thanks.

**Comment by Ph03n1xRt** [comment]
Hello. May I ask how it runs through? I have obtained the dataset from the paper.

**Comment by david-yoon** [comment]
Hi @OnlyAoiKunie , @cuiyimeng 
Sorry for the late response. You may find the code (WA, UA) from another repository below:

https://github.com/david-yoon/attentive-modality-hopping-for-SER/blob/master/util/measure_WA_UA.py
