### ISSUE TITLE
Unable to open link to download IEMOCAP preprocessed dataset

### ISSUE THREAD

**Issue by Jimmy66641** [david-yoon/multimodal-speech-emotion#14]
Hello, David
I've filled out the form to request a dataset, and I've also gotten permission from the IEMOCAP team. But I can not open the download URL. Can you check to see if there's a problem with the URL? I will be grateful for your help!

**Comment by david-yoon** [comment]
@Jimmy66641 Sorry for the inconvenience. The link has broken. Let me know how to contact you (via email). Or you may drop an email to me. I'll provide a new link to you.

**Comment by Jimmy66641** [comment]
> @Jimmy66641 Sorry for the inconvenience. The link has broken. Let me know how to contact you (via email). Or you may drop an email to me. I'll provide a new link to you.

I have contacted you via email and obtained the new download link. Thank you very much!

**Comment by yihaoyao402** [comment]
> @Jimmy66641 Sorry for the inconvenience. The link has broken. Let me know how to contact you (via email). Or you may drop an email to me. I'll provide a new link to you.

Hello, I have the same problem, I also got the license for the dataset, I don't know how to download the processed dataset? Here is my email : 2022110594@stu.njmu.edu.cn   3q！
