### ISSUE TITLE
(WARN) [1] in instance 'lld.reader' : Mismatch in input level buffer sizes (levelconf.nT). Level #0 has size 2 which is smaller than the max. input size of all input levels (10). This might cause the processing to hang unpredictably or cause incomplete processing.

### ISSUE THREAD

**Issue by ramesh720** [david-yoon/multimodal-speech-emotion#2]
when i am running IEMOCAP_01_wav_to_feature.ipynb
i am getting error like this.
i am unable to understand the error . can you please help me

![image](https://user-images.githubusercontent.com/43946769/52420516-39c60900-2b18-11e9-8391-2ce0269cdaef.png)

**Comment by david-yoon** [comment]
Hi, 
It seems the error comes from OpenSmile. I cannot understand the meaning of the error code, either.

I just checked the codes of the "preprocessing" and made it clear. 
Please pull the repository, and use the latest code. ( I tested it )

- put 'IEMOCAP_full_release' folder ( it can be downloaded from the IEMOCAP web page ) to "multimodal-speech-emotion/data/raw/IEMOCAP_full_release'
- run the code in the "multimodal-speech-emotion/preprocessing"
- you will get the processed data in the following folder, "multimodal-speech-emotion/data/processed/"

If you have any errors, please let me know it.

**Comment by ramesh720** [comment]
thank you sir. i will let you know
