### ISSUE TITLE
application of a visiting Ph.D

### ISSUE THREAD

**Issue by Haorotu** [david-yoon/multimodal-speech-emotion#4]
Hi, Dadid
Thanks for your code to help my research. I want to be a visitingPh.D to learn in your university. Could you give me your e-mail to communicate with each other? I want to seek advice from you.
Thanks very much
Yours
Harotu

**Comment by david-yoon** [comment]
Hi Harotu,
I'm happy to hear that the code could help your research.
Let's get in touch with :)

mysmilesh@snu.ac.kr

Thank you,
David

**Comment by Haorotu** [comment]
Hi David, 
I have already sent for your e-mail, and I am keen to receive your reply. Thanks very much.
Best wishes!

Haoruto

**Comment by david-yoon** [comment]
Hi Haoruto,

I received and replied to your mail.

Thank you,
David
